### PR TITLE
Adding images

### PR DESCRIPTION
**Pull request by HassanAkbar**
Adding images to site from glossary

Screenshot 2022-08-26 at 3 33 32 PM

**UPDATED:**

Screenshot 2022-08-29 at 6 13 25 PM

resolves geolexica/isotc204-glossary#12

### CODE REVIEW

**Comment by ronaldtse** [comment]
The images also have metadata, e.g. a caption number and a caption title. We need to somehow embed these together with the images, so they can be re-used.

For `fig_A.23` you can see in:
https://raw.githubusercontent.com/metanorma/iso-14812/main/sources/sections/annex-a.adoc

the caption is:
```
[[fig_A.23]]
.Road reservation component graphic
image::fig_A.23.png[]
```

The figure has this metadata:
* source = "ISO 14812, Figure A.23"
* caption title = "Road reservation component graphic"

Possibly we either need 1 YAML file for all figures, or 1 YAML per figure to store this information.

**Comment by HassanAkbar** [comment]
@ronaldtse Updated the glossary to include a `metadata file` for images and added new image in the description with the updated view.

**Comment by ronaldtse** [comment]
@HassanAkbar can you help make this change? Thanks.

Screen Shot 2022-09-12 at 7 08 08 PM

**Comment by HassanAkbar** [comment]
> @HassanAkbar can you help make this change? Thanks.

@ronaldtse This has been done.

Screenshot 2022-09-12 at 4 53 51 PM

**Comment by ronaldtse** [comment]
Thank you @HassanAkbar !

**Pull request merged**
